version: '3.8'

services:
  web1:
    build:
      context: ./src
    volumes:
      - ./src:/src  # Монтируем исходный код для разработки
    environment:
      SERVER_ID: SERVER-1
    networks:
      - app_network

  web2:
    build:
      context: ./src
    volumes:
      - ./src:/src
    environment:
      SERVER_ID: SERVER-2
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Пробрасываем порт 80 с хоста на контейнер
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Монтируем конфиг Nginx
    depends_on:
      - web1
      - web2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge